### ISSUE TITLE
datasource configurations

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud-configuration#1]
### configuratios
> datasource.yml
```yaml
datasource:
  url: jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password:
```
